context: ../../../../fpga/scanchain/fle6_4x4_cyclefree/ctx.pkl
compiler: vcs
app:
    name: adder
    sources:
        - ../../src/adder.v
constraints:
    io: io.partial
# tests:
#     basic:
#         sources:
#             - ../../src/bcd2bin_test_basic.v
