// Automatically generated by PRGA testbench generator
`timescale 1ns/1ps

// Enable post-syn if post-implementation is enabled
`ifdef PRGA_TEST_POSTIMPL
    `ifndef PRGA_TEST_POSTSYN
        `define PRGA_TEST_POSTSYN
    `endif
`endif

module prga_tb_top;

    // -----------------------------------------------------------------------
    // -- Parameters ---------------------------------------------------------
    // -----------------------------------------------------------------------
    localparam CLK_PERIOD = 10;

    // -----------------------------------------------------------------------
    // -- Signals and DUTs ---------------------------------------------------
    // -----------------------------------------------------------------------

    // Testbench ctrl
    reg f_tb_clk, f_tb_rst;
    wire w_tb_pass, w_tb_fail, w_tb_prog_done;

    // Logging
    reg [31:0] f_tb_verbosity, f_tb_max_cycle, f_tb_cycle_cnt;

    // -- Test ---------------------------------------------------------------
    // Signals
    wire w_test_pulse;
    wire w_test_clk;
    wire [15:0] w_test_out;

    // Tester
    basic i_tester (
        .tb_clk(f_tb_clk)
        ,.tb_rst(f_tb_rst)
        ,.tb_pass(w_tb_pass)
        ,.tb_fail(w_tb_fail)
        ,.tb_prog_done(w_tb_prog_done)
        ,.tb_verbosity(f_tb_verbosity)
        ,.tb_cycle_cnt(f_tb_cycle_cnt)
        ,.pulse(w_test_pulse)
        ,.clk(w_test_clk)
        ,.out(w_test_out)
        );

    // -- Behavioral Model ---------------------------------------------------
    // Signals
    wire [15:0] w_behav_out;

    // DUT
    adder i_behav (
        .pulse(w_test_pulse)
        ,.clk(w_test_clk)
        ,.out(w_behav_out)
        );

    // -- Post-Synthesis Model -----------------------------------------------
`ifdef PRGA_TEST_POSTSYN
    // Signals
    wire [15:0] w_postsyn_out;

    // DUT
    postsyn i_postsyn (
        .pulse(w_test_pulse)
        ,.clk(w_test_clk)
        ,.out(w_postsyn_out)
        );
`endif  // `ifdef PRGA_TEST_POSTSYN

    // -- Post-Implementation Model ------------------------------------------
`ifdef PRGA_TEST_POSTIMPL
    // Signals
    wire [15:0] w_impl_out;

    // DUT
    implwrap i_postimpl (
        .tb_clk(f_tb_clk)
        ,.tb_rst(f_tb_rst)
        ,.tb_prog_done(w_tb_prog_done)
        ,.tb_verbosity(f_tb_verbosity)
        ,.tb_cycle_cnt(f_tb_cycle_cnt)
        ,.pulse(w_test_pulse)
        ,.clk(w_test_clk)
        ,.out(w_impl_out)
        );
`else   // `ifdef PRGA_TEST_POSTIMPL
    assign w_tb_prog_done = 1'b1;
`endif  // `ifdef PRGA_TEST_POSTIMPL

    // -----------------------------------------------------------------------
    // -- Testbench Control Logic --------------------------------------------
    // -----------------------------------------------------------------------

    initial begin
        if (!$value$plusargs("verbosity=%d", f_tb_verbosity)) begin
            f_tb_verbosity = 1;
        end
        
        if (!$value$plusargs("max_cycle=%d", f_tb_max_cycle)) begin
            f_tb_max_cycle = 100_000; // 100K cycles
        end

        if (f_tb_verbosity >= 1)
            $display("[INFO] Max cycle count: %d", f_tb_max_cycle);

        f_tb_clk = 1'b0;
        f_tb_rst = 1'b0;
        f_tb_cycle_cnt = 0;

        #(CLK_PERIOD * 1.25) f_tb_rst = 1'b1;
        #(CLK_PERIOD * 10) f_tb_rst = 1'b0;
    end

    // Testbench clock generator
    always #(CLK_PERIOD / 2.0) f_tb_clk = ~f_tb_clk;

    // Cycle count tracking
    always @(posedge f_tb_clk) begin
        if (f_tb_rst) begin
            f_tb_cycle_cnt <= 0;
        end else begin
            f_tb_cycle_cnt <= f_tb_cycle_cnt + 1;
            if (f_tb_verbosity >= 1 && f_tb_cycle_cnt % 1_000 == 0)
                $display("[INFO] %3dK cycles passed", f_tb_cycle_cnt / 1_000);

            if (w_tb_fail) begin
                $display();
                $display("[INFO] ++=========================++");
                $display("[INFO] ||       TEST FAILED       ||");
                $display("[INFO] ++=========================++");
                $display();
                $finish;
            end else if (w_tb_pass) begin
                $display();
                $display("[INFO] ++=========================++");
                $display("[INFO] ||       TEST PASSED       ||");
                $display("[INFO] ++=========================++");
                $display();
                $finish;
            end

            if (f_tb_cycle_cnt >= f_tb_max_cycle) begin
                $display("[ERROR] Max cycle count reached, killing simulation");
                $finish;
            end
        end
    end

    // -----------------------------------------------------------------------
    // -- Wiring -------------------------------------------------------------
    // -----------------------------------------------------------------------
`ifdef PRGA_TEST_POSTIMPL
    assign w_test_out = w_impl_out;
`else   // `ifdef PRGA_TEST_POSTIMPL
`ifdef PRGA_TEST_POSTSYN
    assign w_test_out = w_postsyn_out;
`else   // `ifdef PRGA_TEST_POSTSYN
    assign w_test_out = w_behav_out;
`endif  // `ifdef PRGA_TEST_POSTSYN
`endif  // `ifdef PRGA_TEST_POSTIMPL

endmodule