#!/usr/bin/env bash

if [ "${BASH_SOURCE-}" = "$0" ]; then
    sourced=0
else
    sourced=1
fi

export PRGA_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

function err() {
    >&2 echo -e "\033[0;31m[ERROR]\033[0m" $@
}

function info() {
    echo -e "\033[0;34m[INFO]\033[0m" $@
}

if [ ! -z "${VIRTUAL_ENV}" ]; then
    err "Already in a Python virtualenv"
    if [ "$sourced" = "1" ]; then return 0; else exit 1; fi
fi

# choose the correct binaries
info "Setting \$PATH"
OLD_PATH=$PATH
export PATH=$PRGA_ROOT/local/bin:$PATH

# path to the uv-generated virtualenv
VENV_ACTIVATE="$PRGA_ROOT/prga.py/.venv/bin/activate"

# activate virtualenv
if [[ "$sourced" == "1" ]]; then
    info "'envscr/activate' sourced ..."

    if [ ! -f "$VENV_ACTIVATE" ]; then
        err "Python virtualenv not created yet. Please run envscr/install first"
        export PATH=${OLD_PATH}
    else
        info "Activating Python virtualenv ..."
        source "$VENV_ACTIVATE"
    fi

else
    info "'envscr/activate' executed ..."

    if [ ! -f "$VENV_ACTIVATE" ]; then
        err "Python virtualenv not created yet. Please run envscr/install first"
        export PATH=${OLD_PATH}
        exit 1
    fi

    CWD=${PWD}
    trap "cd ${CWD} && export PATH=${OLD_PATH}" EXIT
    trap "cd ${CWD} && export PATH=${OLD_PATH}" SIGINT

    pushd $PRGA_ROOT > /dev/null

    info "Entering Python virtualenv in a subshell ..."
    
    # Mimics pipenv shell by starting a bash instance with the venv sourced
    bash --init-file "$VENV_ACTIVATE"
    
    info "Leaving Python virtualenv ..."

    # roll back to the old state
    info "Reverting \$PATH"
    export PATH=$OLD_PATH
    popd > /dev/null

    info "Thanks for using PRGA. We look forward to your next use :)"
fi

# vim: set ft=sh:
