// Automatically generated by PRGA
module prga_magic_bitstream_checker;

    reg fail;

    always @(posedge dut.prog_done) begin
        fail = 1'b0;

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0] != 32'hffff0000) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hffff0000",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32] != 32'hffff0000) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'hffff0000",
                    dut.i_tile_x1y5.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y1.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y2.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y1.i_tile_x0y3.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0] != 32'hf0f0f0f0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hf0f0f0f0",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32] != 32'haaaaaaaa) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'haaaaaaaa",
                    dut.i_tile_x1y5.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64] != 2'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64] == 2'h%h != 2'h0",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32] != 32'hcccccccc) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32] == 32'h%h != 32'hcccccccc",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i0.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h1",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66] != 1'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66] == 1'h%h != 1'h0",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[66:66]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64] == 2'h%h != 2'h2",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[65:64]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0] != 32'hffff0000) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0] == 32'h%h != 32'hffff0000",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[31:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32] != 32'hff00ff00) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'hff00ff00",
                    dut.i_tile_x1y1.i_tile_x0y0.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[69:68] != 2'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h3",
                    dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[67:67] != 1'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[67:67] == 1'h%h != 1'h1",
                    dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[67:67]);
        end

        if (dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[63:32] != 32'h0) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'h0",
                    dut.i_tile_x1y5.i_tile_x3y0.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[69:68] != 2'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[69:68] == 2'h%h != 2'h3",
                    dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[69:68]);
        end

        if (dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[67:67] != 1'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[67:67] == 1'h%h != 1'h1",
                    dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[67:67]);
        end

        if (dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[63:32] != 32'hffffffff) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[63:32] == 32'h%h != 32'hffffffff",
                    dut.i_tile_x1y1.i_tile_x1y1.i_blk.i_cluster_i1.prog_data[63:32]);
        end

        if (dut.i_tile_x0y2.i_blk_i1.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_blk_i1.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y2.i_blk_i1.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y2.i_blk_i2.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_blk_i2.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y2.i_blk_i2.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y2.i_blk_i3.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_blk_i3.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y2.i_blk_i3.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y3.i_blk_i0.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y3.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y3.i_blk_i1.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_blk_i1.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y3.i_blk_i1.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y3.i_blk_i2.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_blk_i2.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y3.i_blk_i2.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y3.i_blk_i3.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_blk_i3.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y3.i_blk_i3.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y4.i_blk_i0.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y4.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y4.i_blk_i1.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_blk_i1.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y4.i_blk_i1.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y4.i_blk_i2.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_blk_i2.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y4.i_blk_i2.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y4.i_blk_i3.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_blk_i3.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y4.i_blk_i3.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y5.i_blk_i0.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y5.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y5.i_blk_i1.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_blk_i1.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y5.i_blk_i1.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y5.i_blk_i2.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_blk_i2.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y5.i_blk_i2.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y5.i_blk_i3.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_blk_i3.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y5.i_blk_i3.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y6.i_blk_i0.io.prog_data[1:0] != 2'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y6.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h2",
                    dut.i_tile_x0y6.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y2.i_blk_i0.io.prog_data[1:0] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h1",
                    dut.i_tile_x0y2.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x0y1.i_blk_i0.io.prog_data[1:0] != 2'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y1.i_blk_i0.io.prog_data[1:0] == 2'h%h != 2'h1",
                    dut.i_tile_x0y1.i_blk_i0.io.prog_data[1:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x1y3se.i_sw_so_x0v1w_L2_2.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x1y3se.i_sw_so_x0v1w_L2_2.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y1.i_sbox_x1y3se.i_sw_so_x0v1w_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h3",
                    dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h3",
                    dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h3",
                    dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x1y3sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x1y3sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x1y3sw.i_sw_so_u1y0n_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_2.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_2.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h9) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h9",
                    dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x1y1sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x1y1sw.i_sw_so_u1y0n_L2_2.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x1y1sw.i_sw_so_u1y0n_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y3se.i_sw_so_x0v1w_L2_3.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y3se.i_sw_so_x0v1w_L2_3.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y3se.i_sw_so_x0v1w_L2_3.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y7ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y7ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y7ne.i_sw_so_x0y0s_L2_16.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h1c) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h1c",
                    dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_16.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h18) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h18",
                    dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h1c) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h1c",
                    dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_16.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_16.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h18) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h18",
                    dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h1c) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h1c",
                    dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_8.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x2y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x1y2se.i_sw_so_x0v1w_L2_17.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x1y2se.i_sw_so_x0v1w_L2_17.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_tile_x1y1.i_sbox_x1y2se.i_sw_so_x0v1w_L2_17.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] != 6'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0] == 6'h%h != 6'h4",
                    dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_0.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h4",
                    dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0] != 6'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0] == 6'h%h != 6'h4",
                    dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0]);
        end

        if (dut.i_tile_x5y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x5y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x5y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x3y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x3y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_tile_x1y5.i_sbox_x3y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x1y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x1y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x1y1se.i_sw_so_x0v1w_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_4.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_4.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y5.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_4.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h7) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h7",
                    dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h7) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h7",
                    dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_4.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_4.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_4.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h7) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h7",
                    dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0] != 6'h9) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0] == 6'h%h != 6'h9",
                    dut.i_tile_x1y5.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_10.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_14.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_5.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_5.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h9) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h9",
                    dut.i_tile_x1y5.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_5.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_5.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h9) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h9",
                    dut.i_tile_x1y5.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h9) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h9",
                    dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_14.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_14.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_14.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h18) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h18",
                    dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y1.i_tile_x0y1.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_9.prog_data[5:0] != 6'h1e) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_9.prog_data[5:0] == 6'h%h != 6'h1e",
                    dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_9.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h18) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h18",
                    dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y1.i_tile_x0y3.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_6.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_6.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_6.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_13.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_13.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_13.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] != 6'h16) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0] == 6'h%h != 6'h16",
                    dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_3.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x1y0ne.i_sw_so_x0y0s_L2_13.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x1y0ne.i_sw_so_x0y0s_L2_13.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y5.i_sbox_x1y0ne.i_sw_so_x0y0s_L2_13.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x1y0se.i_sw_so_x0v1w_L2_6.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x1y0se.i_sw_so_x0v1w_L2_6.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y5.i_sbox_x1y0se.i_sw_so_x0v1w_L2_6.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_12.prog_data[2:0] != 3'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_12.prog_data[2:0] == 3'h%h != 3'h2",
                    dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_12.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h14) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h14",
                    dut.i_tile_x1y1.i_tile_x0y2.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x1y0sw.i_sw_so_u1y0n_L2_6.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x1y0sw.i_sw_so_u1y0n_L2_6.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x1y0sw.i_sw_so_u1y0n_L2_6.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_7.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_7.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_7.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_12.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_12.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_12.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] != 6'h14) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0] == 6'h%h != 6'h14",
                    dut.i_tile_x1y5.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_6.prog_data[5:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y4ne.i_sw_so_x0y0s_L2_19.prog_data[2:0]);
        end

        if (dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] != 7'h4e) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] == 7'h%h != 7'h4e",
                    dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y0se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y5.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] != 7'h49) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] == 7'h%h != 7'h49",
                    dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_19.prog_data[2:0]);
        end

        if (dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] != 7'h4e) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] == 7'h%h != 7'h4e",
                    dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y5ne.i_sw_so_x0y0s_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] != 7'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] == 7'h%h != 7'h6",
                    dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_19.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_19.prog_data[2:0]);
        end

        if (dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] != 7'h50) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] == 7'h%h != 7'h50",
                    dut.i_tile_x0y5.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y5.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_1.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_sbox_x0y6ne.i_sw_so_x0y0s_L2_1.prog_data[2:0]);
        end

        if (dut.i_tile_x0y6.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] != 7'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y6.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] == 7'h%h != 7'h6",
                    dut.i_tile_x0y6.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] != 7'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] == 7'h%h != 7'h3",
                    dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y1ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_17.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_17.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_17.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_17.prog_data[2:0]);
        end

        if (dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] != 7'h47) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] == 7'h%h != 7'h47",
                    dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] != 7'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] == 7'h%h != 7'h3",
                    dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y1se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y1sw.i_sw_so_u1y0n_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] != 7'h4b) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] == 7'h%h != 7'h4b",
                    dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] != 7'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0] == 7'h%h != 7'h1",
                    dut.i_tile_x0y3.i_cbox_e0.i_sw_bp_x0y0i3_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y3ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y2se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y2sw.i_sw_so_u1y0n_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] != 7'h4b) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0] == 7'h%h != 7'h4b",
                    dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i0_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_0.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_0.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_0.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] != 7'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] == 7'h%h != 7'h1",
                    dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y5.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_18.prog_data[2:0] != 3'h3) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_18.prog_data[2:0] == 3'h%h != 3'h3",
                    dut.i_tile_x1y1.i_sbox_x0y3se.i_sw_so_x0v1w_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_18.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y3sw.i_sw_so_u1y0n_L2_18.prog_data[2:0]);
        end

        if (dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] != 7'h49) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] == 7'h%h != 7'h49",
                    dut.i_tile_x0y4.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0]);
        end

        if (dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_sbox_x0y2ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x0y2.i_cbox_e0.i_sw_cu_x0y0s_L2_0.prog_data[2:0] != 3'h1) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_cbox_e0.i_sw_cu_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h1",
                    dut.i_tile_x0y2.i_cbox_e0.i_sw_cu_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_1.prog_data[5:0] != 6'h2) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_1.prog_data[5:0] == 6'h%h != 6'h2",
                    dut.i_tile_x1y1.i_tile_x0y0.i_cbox_w0.i_sw_bp_x0y0i0_in_1.prog_data[5:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_0.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_19.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_19.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_19.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_19.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_19.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_19.prog_data[2:0]);
        end

        if (dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] != 7'h4f) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0] == 7'h%h != 7'h4f",
                    dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i1_outpad.prog_data[6:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] != 3'h6) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0] == 3'h%h != 3'h6",
                    dut.i_tile_x1y1.i_sbox_x0y0ne.i_sw_so_x0y0s_L2_2.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_17.prog_data[2:0] != 3'h4) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_17.prog_data[2:0] == 3'h%h != 3'h4",
                    dut.i_tile_x1y1.i_sbox_x0y0se.i_sw_so_x0v1w_L2_17.prog_data[2:0]);
        end

        if (dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] != 3'h5) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_17.prog_data[2:0] == 3'h%h != 3'h5",
                    dut.i_tile_x1y1.i_sbox_x0y0sw.i_sw_so_u1y0n_L2_17.prog_data[2:0]);
        end

        if (dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] != 7'h47) begin
            fail = 1'b1;
            $display("[ERROR] dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0] == 7'h%h != 7'h47",
                    dut.i_tile_x0y2.i_cbox_e0.i_sw_bp_x0y0i2_outpad.prog_data[6:0]);
        end

        if (fail) begin
            $display("[ERROR] Magic bitstream check failed. See ERRORs above.");
            $finish;
        end else begin
            $display("[INFO] Magic bitstream check passed. The bitstream seems to be loaded correctly.");
        end

    end

endmodule
