/* Generated by Yosys 0.42+40 (git sha1 dac5bd198, g++ 13.3.0-6ubuntu2~24.04 -fPIC -Os) */

/* dynports =  1  */
/* top =  1  */
/* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:1.1-20.10" */
module postsyn(pulse, clk, out);
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  wire [15:0] \$0\out[15:0] ;
  wire [14:0] \$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY ;
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:19.24-19.29" */
  /* unused_bits = "15" */
  wire [15:0] \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY ;
  /* keep = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:9.28-9.29" */
  wire [14:0] a;
  /* keep = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:10.28-10.29" */
  wire [14:0] b;
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:5.16-5.19" */
  input clk;
  wire clk;
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:6.25-6.28" */
  output [15:0] out;
  reg [15:0] out = 16'h0000;
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:4.16-4.21" */
  input pulse;
  wire pulse;
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:21.33-21.97" */
  m_adder #(
    .CIN_MODE(2'h0)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.cc_first  (
    .a(1'h1),
    .b(pulse),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [0]),
    .s(\$0\out[15:0] [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[10].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [9]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [10]),
    .s(\$0\out[15:0] [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[11].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [10]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [11]),
    .s(\$0\out[15:0] [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[12].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [11]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [12]),
    .s(\$0\out[15:0] [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[13].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [12]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [13]),
    .s(\$0\out[15:0] [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[14].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [13]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [14]),
    .s(\$0\out[15:0] [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[15].cc  (
    .a(1'h0),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [14]),
    .cout(\$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [15]),
    .s(\$0\out[15:0] [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[1].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [0]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [1]),
    .s(\$0\out[15:0] [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[2].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [1]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [2]),
    .s(\$0\out[15:0] [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[3].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [2]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [3]),
    .s(\$0\out[15:0] [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[4].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [3]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [4]),
    .s(\$0\out[15:0] [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[5].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [4]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [5]),
    .s(\$0\out[15:0] [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[6].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [5]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [6]),
    .s(\$0\out[15:0] [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[7].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [6]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [7]),
    .s(\$0\out[15:0] [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[8].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [7]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [8]),
    .s(\$0\out[15:0] [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17.12-17.17|/workspace/prga_physical/prga/examples/fpga/scanchain/fle6_N2_mem2K_8x8/syn/m_adder.techmap.v:25.37-25.113" */
  m_adder #(
    .CIN_MODE(2'h2)
  ) \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.genblk1[9].cc  (
    .a(1'h1),
    .b(1'h0),
    .cin(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [8]),
    .cout(\$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [9]),
    .s(\$0\out[15:0] [9])
  );
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[0] <= \$0\out[15:0] [0];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[1] <= \$0\out[15:0] [1];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[2] <= \$0\out[15:0] [2];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[3] <= \$0\out[15:0] [3];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[4] <= \$0\out[15:0] [4];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[5] <= \$0\out[15:0] [5];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[6] <= \$0\out[15:0] [6];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[7] <= \$0\out[15:0] [7];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[8] <= \$0\out[15:0] [8];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[9] <= \$0\out[15:0] [9];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[10] <= \$0\out[15:0] [10];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[11] <= \$0\out[15:0] [11];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[12] <= \$0\out[15:0] [12];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[13] <= \$0\out[15:0] [13];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[14] <= \$0\out[15:0] [14];
  /* src = "/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:16.1-18.4" */
  always @(posedge clk)
    out[15] <= \$0\out[15:0] [15];
  assign \$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY [14:0] = \$abc$449$add$/workspace/prga_physical/prga/examples/app/8bitadd/src/adder.v:17$260.CARRY ;
  assign a = 15'h7fff;
  assign b = { 14'h0000, pulse };
endmodule
